### ISSUE TITLE
impressive!

### ISSUE THREAD

**Issue by hopewise** [SempaiGames/extension-harfbuzz#1]
Hi
I would like to thank you for this useful extension.

I like to know please, is this cross platform extension? Would it work on PC too?

Also, can it be used to input text? Ex: using haxeui? Or its for text output only?

**Comment by DanielUranga** [comment]
Hi
Thanks!

This is a cpp extension, should work on all cpp targets (including PC).

I havent implemented text input, only showing text. I guess its possible to implement text input by listening to keyboard events.
