### ISSUE TITLE
Support On Linux?

### ISSUE THREAD

**Issue by ghost** [SempaiGames/extension-harfbuzz#3]
Hey what might I have to do to get this supported on Linux Targets?

When I try to compile for that target I am met with a message about a missing ndll.  I'd be happy to put in some effort to make this work, but I'm not sure where to start.

**Comment by fbricker** [comment]
have you tried running this first?

``` bash
lime rebuild extension-harfbuzz linux
```

**Comment by ghost** [comment]
Rad that did it. Thanks.
